
export const Dropdown = () => import(/* webpackChunkName: "shared" */ '@/Shared/Dropdown')
export const FileInput = () => import(/* webpackChunkName: "shared" */ '@/Shared/FileInput')
export const FlashMessages = () => import(/* webpackChunkName: "shared" */ '@/Shared/FlashMessages')
export const Icon = () => import(/* webpackChunkName: "shared" */ '@/Shared/Icon')
export const Layout = () => import(/* webpackChunkName: "shared" */ '@/Shared/Layout')
export const LoadingButton = () => import(/* webpackChunkName: "shared" */ '@/Shared/LoadingButton')
export const Logo = () => import(/* webpackChunkName: "shared" */ '@/Shared/Logo')
export const MainMenu = () => import(/* webpackChunkName: "shared" */ '@/Shared/MainMenu')
export const Pagination = () => import(/* webpackChunkName: "shared" */ '@/Shared/Pagination')
export const SearchFilter = () => import(/* webpackChunkName: "shared" */ '@/Shared/SearchFilter')
export const TextareaInput = () => import(/* webpackChunkName: "shared" */ '@/Shared/TextareaInput')
export const TextInput = () => import(/* webpackChunkName: "shared" */ '@/Shared/TextInput')
export const TrashedMessage = () => import(/* webpackChunkName: "shared" */ '@/Shared/TrashedMessage')
export const UmbricLogo = () => import(/* webpackChunkName: "shared" */ '@/Shared/UmbricLogo')
export const RadioButtons = () => import(/* webpackChunkName: "shared" */ '@/Shared/RadioButtons')
export const UmbricLogoPng = () => import(/* webpackChunkName: "shared" */ '@/Shared/UmbricLogoPng')
